[project]
name = "ipmg"
version = "1.0.3"
description = "IP Management & Ping Monitoring CLI Tool"
authors = [{ name = "Sameer Alam" }]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

dependencies = [
    "pandas>=2.0",
    "tqdm>=4.65",
    "openpyxl>=3.1",
    "rich>=13.0",
]
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]

[project.scripts]
ipmg = "ipmg.cli.commands:run"


# ---------- SETUPTOOLS (SRC LAYOUT SUPPORT) ----------
[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]


# ---------- PYTEST ----------
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]


# ---------- RUFF ----------
[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "C90"]
ignore = ["E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
known-first-party = ["ipmg"]


# ---------- BLACK ----------
[tool.black]
line-length = 100
target-version = ["py310"]


# ---------- DEV TOOLING ----------
[dependency-groups]
dev = [
    "pre-commit>=3.5.0",
    "twine>=6.1.0",
]
